all:
  children:
    system:
      hosts:
        test-sys-cont:
          additional_disk_device_path: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_incus_data
          ansible_host: 10.10.30.10
          fq_hostname: test-sys-cont.local
          net_default_gateway: 10.10.30.1
          net_dns: 10.10.30.3
          static_ipv4_to_use: 10.10.30.10
    tofu_vars:
      children:
        system: {}
