---
# Install Collections and Roles with Ansible Galaxy
# ansible-galaxy install -r ansible_requirements.yml

collections:
  - name: community.general
  - name: ansible.posix

roles:
  # - src: git@github.com:xxxxx/xxxxx.git
  #   scm: git
  #   version: xxxxx
  #   name: xxxxx